### ISSUE TITLE
Upstream status tracking

### ISSUE THREAD

**Issue by samueldr** [Tow-Boot/Tow-Boot#2]
*This locked post serves as a wiki-like issue for maintainers to post links to in-progress work at upstream.*

* * *

# Patches to upstream next

 - [ ] https://github.com/Tow-Boot/Tow-Boot/blob/38a0e77a2b79b3e95f3270f384a8913dd70248f8/support/u-boot/2022.07/patches/0001-smbios-enclosure-support.patch

# Patches tracked for upstream

# Patches accepted an merged upstream

 - [x] https://patchwork.ozlabs.org/project/uboot/patch/20211220181916.28327716.samuel@dionne-riel.com/
 - [x] https://patchwork.ozlabs.org/project/uboot/patch/20211220182345.52e0d6f9.samuel@dionne-riel.com/
 - [x] https://patchwork.ozlabs.org/project/uboot/patch/20211220183156.1910e71b.samuel@dionne-riel.com/
 - *pause patch*
     - ~~https://patchwork.ozlabs.org/project/uboot/patch/20211220224946.033b3f99.samuel@dionne-riel.com/~~
     - ~~https://patchwork.ozlabs.org/project/uboot/patch/20220817221549.21831960.samuel@dionne-riel.com/~~
     - [x] https://patchwork.ozlabs.org/project/uboot/patch/20220818154404.70e84f5a.samuel@dionne-riel.com/

* * *

> Hi, right now we're just getting started, and trying to bite a huge chunk all at once. Please politely pester us to get started sending changes back!
