### ISSUE TITLE
Pinebook pro keyboard randomly(?) freezes

### ISSUE THREAD

**Issue by samueldr** [Tow-Boot/Tow-Boot#57]
The issue had been reported on the Matrix room, but never filed here.

Accidentally, or mindfully, touching the touchpad will break keyboard input on the Pinebook Pro.

The workaround is to not touch the touchpad.

### TODO

 - [x] ~~Verify if a keyboard+mouse exhibits the same issue on another board~~ (could not reproduce)
 - [x] ~~Verify with mouse on **the same USB device** (e.g. test with my "air mouse" remote thingy)~~ (could not reproduce)
 - [x] ~~Verify touchpad on Pinebook A64 (could not reproduce)~~

**Comment by charims** [comment]
I had no idea it was the touchpad doing it, I thought it was just being inconsistent! Thanks for the workaround. FDE with grub EFI works just fine now as long as i dont touch the touchpad!

**Comment by vincele** [comment]
I can confirm it's the touchpad.

TB 2021.10-005 on sdcard.
emmc disconnected.
spi empty.

The serial console is unaffected and can continue to move between options and choose one.

Choosing the `Rescan USB` menu entry made the pbp keyboard back usable.
